apiVersion: v1
data:
  ENABLE_LEADER_ELECTION: "false"
  METRICS_ADDR_CTRL_MGR: "0"
  METRICS_ADDR_SVC_MGR: ":8080"
  PARTITION_ID: sample-partition
  TENANT: sample-tenant
  LOAD_BALANCER_IP: "127.0.0.1"
  PORT_RANGE_START: 31767
  PORT_RANGE_SIZE: 8192
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: controller-manager-configmap
  namespace: system
